# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.215'
  hooks:
      - id: ruff
          # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude", "--config=./ruff.toml"]
-   repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
    - id: black
